In [1]:
import pandas as pd
from sqlalchemy import create_engine
import psycopg2

In [2]:
data_in_dir = r"../data/"

gw_station_fname = r"opendata_messstelle.csv"

gw_station_pfname = data_in_dir + gw_station_fname

In [3]:
df = pd.read_csv(gw_station_pfname, delimiter=';', header='infer')

In [12]:
df.e32

0        343064
1        292077
2        287141
3        309490
4        316741
          ...
71115    468938
71116    3338xx
71117    331861
71118    3604xx
71119    3379xx
Name: e32, Length: 71120, dtype: object

In [13]:
df = df.dropna(subset=['e32'])
df = df.dropna(subset=['n32'])

In [14]:
df.e32

0        343064
1        292077
2        287141
3        309490
4        316741
          ...
71115    468938
71116    3338xx
71117    331861
71118    3604xx
71119    3379xx
Name: e32, Length: 71119, dtype: object

In [15]:

df.e32 = (df.e32.str[:-2]+"50").astype(int)
df.n32 = (df.n32.str[:-2]+"50").astype(int)

In [16]:
df.e32

0        343050
1        292050
2        287150
3        309450
4        316750
          ...
71115    468950
71116    333850
71117    331850
71118    360450
71119    337950
Name: e32, Length: 71119, dtype: int32

In [20]:
df.dtypes

sl_nr                             int64
messstelle_id                     int64
name                             object
e32                               int32
n32                               int32
gw_stockwerk                    float64
grundstueck                      object
gemeinde_id                      object
gwhorizont_id                    object
gwhorizont                       object
gwleiter_id                      object
gwleiter                         object
einrichtungsgrund                object
gwk_lage_auf_id                  object
gwk_lage_id                      object
gwk_monitoring_auf_id            object
gwk_monitoring_id                object
messprogramm                     object
turnus_wasserstand               object
freigabe_wstd                    object
freigabe_chemie                  object
freigabe_lage                    object
wasserstandsmessstelle           object
guetemessstelle                  object
im_wrrl_messnetz_chemie          object
im_wrrl_messnetz_wasserstand     object
messstellenart                   object
wasserart                        object
labor                            object
beobachtung_wasserstand          object
eigentuemer                      object
betreiber                        object
filterlaenge_cm                 float64
sumpfrohrlaenge_cm              float64
ausbaudurchmesser_mm            float64
historischer_ruhe_wsp           float64
einbaulaenge_cm                 float64
oberkante_filter_cm             float64
unterkante_filter_cm            float64
dtype: object

In [27]:
import geopandas as gpd
from shapely.geometry import Point

In [29]:
gdf = gpd.GeoDataFrame(df, geometry=gpd.points_from_xy(df.e32, df.n32), crs="EPSG:25832")

In [33]:
gdf

,sl_nr,messstelle_id,name,e32,n32,gw_stockwerk,grundstueck,gemeinde_id,gwhorizont_id,gwhorizont,...,eigentuemer,betreiber,filterlaenge_cm,sumpfrohrlaenge_cm,ausbaudurchmesser_mm,historischer_ruhe_wsp,einbaulaenge_cm,oberkante_filter_cm,unterkante_filter_cm,geometry
0,67530,32505929,UWB-Ddorf 01285,343050,5678050,1.0,,05111000,NaN,NaN,...,Stadt Düsseldorf ...,Stadt Düsseldorf ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (343050.000 5678050.000)
1,51044,10446746,60GP012303,292050,5645350,NaN,privat,NL000882,5,Zwischenmittel,...,Prov. Limburg (NL) ...,Prov. Limburg (NL) ...,200.0,NaN,NaN,NaN,16893.0,-3333.0,-3533.0,POINT (292050.000 5645350.000)
2,51070,87005323,58BP024606,287150,5684650,NaN,privat,NL001640,6D,Neurather Sand,...,Prov. Limburg (NL) ...,Prov. Limburg (NL) ...,500.0,300.0,NaN,NaN,32667.0,-29083.0,-29583.0,POINT (287150.000 5684650.000)
3,68442,80000290,Krinsend 0079 neu,309450,5678050,1.0,,05166024,NaN,NaN,...,Land NRW ...,NaN,NaN,NaN,NaN,NaN,1517.0,4832.0,4832.0,POINT (309450.000 5678050.000)
4,68518,86583852,WG102GM93-3,316750,5680250,NaN,privat,05166032,NaN,NaN,...,NiederrheinWasser GmbH (ehem. Niederheinwerke)...,NiederrheinWasser GmbH (ehem. Niederheinwerke)...,200.0,NaN,80.0,NaN,5400.0,1413.0,1213.0,POINT (316750.000 5680250.000)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71115,15459,94170393,Quelle Rappelspring,468950,5678650,NaN,oeffentlich,05958048,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (468950.000 5678650.000)
71116,71772,46201555,PAG Hülsdonk,333850,5702650,1.0,,05170024,NaN,NaN,...,Lineg ...,Lineg ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (333850.000 5702650.000)
71117,57904,11007540,Quelle Unterurholz,331850,5604450,1.0,oeffentlich,05366028,SM,Mittlerer Buntsandstein,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (331850.000 5604450.000)
71118,66958,31040196,Br.1 KA Gruiten BRW,360450,5677050,NaN,privat,05158008,NaN,NaN,...,Bergisch-Rheinischer Wasserverband ...,Bergisch-Rheinischer Wasserverband ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (360450.000 5677050.000)
71119,71846,46201920,PAG Pelderweg,337950,5711650,1.0,,05170032,NaN,NaN,...,Lineg ...,Lineg ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (337950.000 5711650.000)

In [31]:
gdf.to_csv("test3.csv")

In [ ]:
# write your sql url below
engine = sqlalchemy.create_engine("postgresql://xxxxxxxxxxxxxxxxxx")

In [ ]:
%time gdf.to_sql(con=engine, name="messstelle", schema="sina", if_exists="replace", index=False)